name: YouTube Buzz Detector

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 依存関係をインストール
        run: npm install

      - name: スクリプトを実行
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node scripts/fetch_and_notify.js
